apiVersion: v2
name: todo-app
description: Todo Chatbot Application - Frontend (Next.js) + Backend (FastAPI)
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - todo
  - chatbot
  - nextjs
  - fastapi
  - kubernetes
maintainers:
  - name: Developer
home: https://github.com/todo-chatbot
